title: <p align="center"> Tien Tran </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/tientranngocthao/">LinkedIn</a> |
  <a href="https://github.com/tnthaotien">GitHub</a>
  </p>
  
  <p align="justify">
  <b>Toolbox:</b> Power BI, Power Query, advanced Excel (PivotTables, XLOOKUP, VBA), basic SQL; familiarity with SAP/ERP/CRM.<br><br>
  <br><br>
  
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

